package: serpent
user: ijstokes

platform:
  - linux-64

engine:
  - python=2.6
  - python=2.7
  - python=3.3
  - python=3.4
  - python=3.5

script:
  - conda build ./conda.recipe/

build_targets: conda
