package:
  name: serpent
  version: 1.12

source:
  git_rev: v1.12
  git_url: git@github.com:ijstokes/Serpent.git

build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - gensim = gensim:main
    #
    # Would create an entry point called gensim that calls gensim.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - serpent


about:
  home: https://pypi.python.org/pypi/serpent
  license: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
