package:
  name: serpent
  version: 1.12

source:
  git_rev: "v1.12"
  path: "git@github.com:ijstokes/Serpent.git"

build:
  number: 2

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - serpent


about:
  home: https://pypi.python.org/pypi/serpent
  license: MIT
